# Generated by Django 6.0.5 on 2026-06-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('DENTIST', 'Dentist'), ('ADMIN', 'Admin'), ('STAFF', 'Staff')], max_length=10),
        ),
    ]
