# Generated by Django 6.0.5 on 2026-06-11 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='phone',
        ),
    ]
