# Generated by Django 6.0.5 on 2026-06-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_patientprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('REGISTER', 'Register'), ('EMAIL_VERIFICATION', 'Email Verification'), ('RESET', 'Reset')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=20),
        ),
    ]
