# Generated by Django 6.0.5 on 2026-06-21 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='procedure',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_procedures', to='core.procedure'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='type',
            field=models.CharField(choices=[('main', 'Main'), ('objective', 'Objective')], default='objective', max_length=255),
        ),
    ]
