# Generated by Django 6.0.5 on 2026-06-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_procedure_options_procedure_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
