# Generated by Django 6.0.5 on 2026-06-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_procedure_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMethodPayloadStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
