# Generated by Django 6.0.5 on 2026-06-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_postmethodpayloadstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmethodpayloadstore',
            name='payload_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
