# Generated by Django 6.0.5 on 2026-06-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_postmethodpayloadstore_payload_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licenseregistrationauthority',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='licenseregistrationauthority',
            table=None,
        ),
    ]
