# Generated by Django 6.0.5 on 2026-06-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_licenseregistrationauthority_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('smtp', 'Smtp'), ('api', 'Api')], default='smtp', max_length=25, null=True)),
                ('server', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('host_user', models.CharField(blank=True, max_length=255, null=True)),
                ('host_password', models.CharField(blank=True, max_length=255, null=True)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.CharField(blank=True, max_length=10, null=True)),
                ('tls', models.BooleanField(default=True)),
                ('api_key', models.CharField(blank=True, max_length=500, null=True)),
                ('ssl', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('today_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('daily_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('today_date', models.DateField(blank=True, null=True)),
                ('today_complete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
