# Generated by Django 6.0.5 on 2026-05-14 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('analytics', '0001_initial'),
        ('dentist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdvscorelog',
            name='dentist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdv_score_logs', to='dentist.dentistprofile'),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='dentist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_log', to='dentist.dentistprofile'),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_log', to='account.patientprofile'),
        ),
    ]
