# Generated by Django 6.0.5 on 2026-06-10 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DentistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('experience_years', models.IntegerField()),
                ('is_claimed', models.BooleanField(default=False)),
                ('rating_avg', models.FloatField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('rdv_score', models.FloatField(default=0)),
                ('response_time_avg', models.FloatField(default=0)),
                ('verification_phase', models.IntegerField(choices=[('LICENSE', 'License'), ('OPERATIONALOperational', 'Two'), ('CLINICALClinical', 'Three')], default='LICENSE')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dentists', to='dentist.clinic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DentistAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_address', to='dentist.dentistprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DentistVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('License_verification', models.BooleanField(default=False)),
                ('operations_verification', models.BooleanField(default=False)),
                ('clinical_verification', models.BooleanField(default=False)),
                ('face_match_score', models.FloatField(null=True)),
                ('dentist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_verification', to='dentist.dentistprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DentistLicenseVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional_headshot', models.ImageField(blank=True, null=True, upload_to='documents/headshot/')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('registration_no', models.CharField(max_length=100)),
                ('doc_type', models.CharField(choices=[('LICENSE', 'License'), ('CERTIFICATE', 'Certificate'), ('INSURANCE', 'Insurance')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/license/')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('NEED_MORE_EVIDENCE', 'Need More Evidence'), ('RESUBMIT_REQUIRED', 'Resubmit Required'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='SUBMITTED', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('registration_authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dentist_license', to='core.licenseregistrationauthority')),
                ('dentist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_license_verification', to='dentist.dentistprofile')),
                ('verification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_license_verification', to='dentist.dentistverification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicOperationVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('NEED_MORE_EVIDENCE', 'Need More Evidence'), ('RESUBMIT_REQUIRED', 'Resubmit Required'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='SUBMITTED', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operation_verification', to='dentist.clinic')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dentist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operation_verification', to='dentist.dentistprofile')),
                ('verification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operation_verification', to='dentist.dentistverification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicalPathVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('NEED_MORE_EVIDENCE', 'Need More Evidence'), ('RESUBMIT_REQUIRED', 'Resubmit Required'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='SUBMITTED', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_path_verification', to='dentist.clinic')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_reviews', to=settings.AUTH_USER_MODEL)),
                ('dentist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_path_verification', to='dentist.dentistprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dentist.dentistprofile')),
                ('verification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_path_verification', to='dentist.dentistverification')),
            ],
            options={
                'db_table': 'clinical_path_verifications',
            },
        ),
        migrations.CreateModel(
            name='NoSurpriseGuarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_variation_percent', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('signer_name', models.CharField(max_length=255)),
                ('typed_signature', models.CharField(max_length=255)),
                ('accepted_terms', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('operation_verification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='no_surprise_guarantee', to='dentist.clinicoperationverification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcedurePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('option_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures_feature', to='dentist.dentistprofile')),
                ('operation_verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures_feature', to='dentist.clinicoperationverification')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_procedures_feature', to='core.procedure')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureMaterialVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(max_length=255)),
                ('ce_certificate', models.FileField(blank=True, null=True, upload_to='documents/material-document/')),
                ('material_brands', models.FileField(blank=True, null=True, upload_to='documents/material-document/')),
                ('invoice', models.FileField(blank=True, null=True, upload_to='documents/material-document/')),
                ('protocol_pdf', models.FileField(blank=True, null=True, upload_to='documents/material-document/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('clinical_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_material_verifications', to='dentist.clinicalpathverification')),
                ('own_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_material_verifications', to='dentist.procedureprice')),
            ],
            options={
                'db_table': 'procedure_material_verification',
            },
        ),
        migrations.CreateModel(
            name='SlotException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('BOOKED', 'Booked'), ('UNAVAILABLE', 'Unavailable'), ('AVAILABLE', 'Available'), ('FREEZED', 'Freezed')], default='BOOKED', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_exceptions', to='appointments.appointment')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_exceptions', to='dentist.dentistprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SterilizationVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_jci_certificate', models.BooleanField(default=False)),
                ('jci_certificate', models.FileField(blank=True, null=True, upload_to='documents/jci/')),
                ('certificate_number', models.CharField(blank=True, max_length=255)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('issuing_authority', models.CharField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('operation_verification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sterilization_verification', to='dentist.clinicoperationverification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SterilizationWalkthrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('walkthrough_video', models.FileField(blank=True, null=True, upload_to='documents/sterilization-videos/')),
                ('autoclave_brand', models.CharField(max_length=255)),
                ('sealed_pouch_visible', models.BooleanField(default=False)),
                ('ultrasonic_cleaner_available', models.BooleanField(default=False)),
                ('cycle_frequency', models.CharField(max_length=255)),
                ('sterilization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='walkthrough', to='dentist.sterilizationverification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DentistWeeklyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], max_length=10)),
                ('day_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OFF', 'Off'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_availability', to='dentist.dentistprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['dentist', 'day_of_week'], name='dentist_den_dentist_b8c11e_idx')],
                'unique_together': {('dentist', 'day_of_week')},
            },
        ),
        migrations.AddConstraint(
            model_name='procedureprice',
            constraint=models.UniqueConstraint(fields=('dentist', 'procedure'), name='unique_dentist_procedure_price'),
        ),
    ]
