# Generated by Django 6.0.5 on 2026-05-14 14:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DentistProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('experience_years', models.IntegerField()),
                ('is_claimed', models.BooleanField(default=False)),
                ('rating_avg', models.FloatField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('rdv_score', models.FloatField(default=0)),
                ('response_time_avg', models.FloatField(default=0)),
                ('verification_phase', models.IntegerField(choices=[('Identity', 'One'), ('Operational', 'Two'), ('Clinical', 'Three')], default='Identity')),
                ('is_verified', models.BooleanField(default=False)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dentists', to='dentist.clinic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DentistService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_services', to='dentist.dentistprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DentistVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_number', models.CharField(max_length=100)),
                ('license_verified', models.BooleanField(default=False)),
                ('identity_verified', models.BooleanField(default=False)),
                ('sterilization_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEW', 'Review'), ('APPROVED', 'Approved'), ('REJECT', 'Reject')], default='PENDING', max_length=20)),
                ('face_match_score', models.FloatField(null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('dentist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_verification', to='dentist.dentistprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DentistDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('License', 'License'), ('Certificate', 'Certificate'), ('Insurance', 'Insurance')], max_length=20)),
                ('file', models.FileField(upload_to='documents/')),
                ('is_verified', models.BooleanField(default=False)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_documents', to='dentist.dentistprofile')),
                ('verification_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_documents', to='dentist.dentistverification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SlotException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('BOOKED', 'Booked'), ('UNAVAILABLE', 'Unavailable'), ('AVAILABLE', 'Available'), ('FREEZED', 'Freezed')], default='BOOKED', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_exceptions', to='appointments.appointment')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_exceptions', to='dentist.dentistprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DentistWeeklyAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], max_length=10)),
                ('day_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OFF', 'Off'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_availability', to='dentist.dentistprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['dentist', 'day_of_week'], name='dentist_den_dentist_b8c11e_idx')],
                'unique_together': {('dentist', 'day_of_week')},
            },
        ),
    ]
