# Generated by Django 6.0.5 on 2026-06-10 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0002_dentistprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentistprofile',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dentists', to='dentist.clinic'),
        ),
        migrations.AlterField(
            model_name='dentistprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
