# Generated by Django 6.0.5 on 2026-06-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0003_alter_dentistprofile_clinic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentistprofile',
            name='verification_phase',
            field=models.CharField(choices=[('LICENSE', 'License'), ('OPERATIONALOperational', 'Two'), ('CLINICALClinical', 'Three')], default='LICENSE'),
        ),
    ]
