# Generated by Django 6.0.5 on 2026-06-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0004_alter_dentistprofile_verification_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentistprofile',
            name='specialty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
