# Generated by Django 6.0.5 on 2026-06-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0005_alter_dentistprofile_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentistprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dentistprofile',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
