# Generated by Django 6.0.5 on 2026-06-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0006_alter_dentistprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentistaddress',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dentistaddress',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dentistaddress',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dentistlicenseverification',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dentistlicenseverification',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
