# Generated by Django 6.0.5 on 2026-06-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0007_alter_dentistaddress_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentistprofile',
            name='specialty',
            field=models.CharField(blank=True, choices=[('PERIODONTIST', 'Periodontist'), ('DENTIST', 'Dentist'), ('SURGEON', 'Surgeon')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dentistprofile',
            name='verification_phase',
            field=models.CharField(choices=[('LICENSE', 'License'), ('OPERATIONAL', 'Operational'), ('CLINICAL', 'Clinical')], default='LICENSE'),
        ),
    ]
