# Generated by Django 6.0.5 on 2026-06-11 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0008_alter_dentistprofile_specialty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dentistverification',
            old_name='License_verification',
            new_name='license_verification',
        ),
        migrations.RemoveField(
            model_name='sterilizationwalkthrough',
            name='cycle_frequency',
        ),
        migrations.AlterField(
            model_name='clinicoperationverification',
            name='clinic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_verification', to='dentist.clinic'),
        ),
        migrations.AlterField(
            model_name='dentistlicenseverification',
            name='doc_type',
            field=models.CharField(choices=[('LICENSE', 'License'), ('CERTIFICATE', 'Certificate'), ('INSURANCE', 'Insurance')], default='LICENSE', max_length=20),
        ),
        migrations.AlterField(
            model_name='dentistprofile',
            name='verification_phase',
            field=models.CharField(choices=[('LICENSE', 'License'), ('OPERATIONAL', 'Operational'), ('CLINICAL', 'Clinical'), ('COMPLETE', 'Complete')], default='LICENSE'),
        ),
        migrations.AlterField(
            model_name='sterilizationwalkthrough',
            name='autoclave_brand',
            field=models.BooleanField(default=False),
        ),
    ]
