# Generated by Django 6.0.5 on 2026-06-13 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0009_rename_license_verification_dentistverification_license_verification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalpathverification',
            name='clinic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_path_verification', to='dentist.clinic'),
        ),
    ]
