# Generated by Django 6.0.5 on 2026-06-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0011_alter_clinicalpathverification_verified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentistverification',
            name='clinical_verification',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('FAILED', 'Failed'), ('REJECT', 'Reject')], default='PENDING'),
        ),
        migrations.AlterField(
            model_name='dentistverification',
            name='license_verification',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('FAILED', 'Failed'), ('REJECT', 'Reject')], default='PENDING'),
        ),
        migrations.AlterField(
            model_name='dentistverification',
            name='operations_verification',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('FAILED', 'Failed'), ('REJECT', 'Reject')], default='PENDING'),
        ),
    ]
