# Generated by Django 6.0.5 on 2026-06-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0012_alter_dentistverification_clinical_verification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentistverification',
            name='face_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
