# Generated by Django 6.0.5 on 2026-06-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0013_alter_dentistverification_face_match_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentistverification',
            name='clinical_verification',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMIT', 'Submit'), ('APPROVED', 'Approved'), ('FAILED', 'Failed'), ('REJECT', 'Reject')], default='PENDING'),
        ),
        migrations.AlterField(
            model_name='dentistverification',
            name='license_verification',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMIT', 'Submit'), ('APPROVED', 'Approved'), ('FAILED', 'Failed'), ('REJECT', 'Reject')], default='PENDING'),
        ),
        migrations.AlterField(
            model_name='dentistverification',
            name='operations_verification',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMIT', 'Submit'), ('APPROVED', 'Approved'), ('FAILED', 'Failed'), ('REJECT', 'Reject')], default='PENDING'),
        ),
    ]
