# Generated by Django 6.0.5 on 2026-06-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0014_alter_dentistverification_clinical_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sterilizationverification',
            name='walkthrough_video',
            field=models.FileField(blank=True, null=True, upload_to='documents/sterilization-videos/'),
        ),
        migrations.AlterField(
            model_name='sterilizationverification',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='SterilizationWalkthrough',
        ),
    ]
