# Generated by Django 6.0.5 on 2026-06-22 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0015_sterilizationverification_walkthrough_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentistWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dentist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='dentist.dentistprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
