# Generated by Django 6.0.5 on 2026-06-22 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0017_remove_escrowpayment_failure_reason_and_more'),
        ('dentist', '0016_dentistwallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentistWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('WITHDRAW', 'Withdraw')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='dentist.dentistwallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
