# Generated by Django 6.0.5 on 2026-06-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0017_dentistwallettransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedurematerialverification',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='procedurematerialverification',
            name='notes',
        ),
        migrations.AddField(
            model_name='dentistwallet',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
