# Generated by Django 6.0.5 on 2026-06-24 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0018_remove_procedurematerialverification_brand_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dentistlicenseverification',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dentistprofile',
            name='verification_phase',
            field=models.CharField(choices=[('LICENSE', 'License'), ('OPERATIONAL', 'Operational'), ('CLINICAL', 'Clinical'), ('IN_REVIEW', 'In Review'), ('COMPLETE', 'Complete')], default='LICENSE'),
        ),
    ]
