# Generated by Django 6.0.5 on 2026-06-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0019_dentistlicenseverification_verified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentistprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
