# Generated by Django 6.0.5 on 2026-05-14 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('appointments', '0001_initial'),
        ('dentist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='dentist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='dentist.dentistprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='account.patientprofile'),
        ),
        migrations.AddField(
            model_name='estimaterequest',
            name='dentist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_requests', to='dentist.dentistprofile'),
        ),
        migrations.AddField(
            model_name='estimaterequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_requests', to='account.patientprofile'),
        ),
        migrations.AddField(
            model_name='estimateresponse',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_response', to='appointments.estimaterequest'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='estimate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.estimateresponse'),
        ),
        migrations.AddField(
            model_name='payment',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='refund',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='appointments.payment'),
        ),
        migrations.AddField(
            model_name='review',
            name='dentist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dentist.dentistprofile'),
        ),
        migrations.AddField(
            model_name='review',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='account.patientprofile'),
        ),
    ]
