# Generated by Django 6.0.5 on 2026-06-10 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('appointments', '0001_initial'),
        ('core', '0001_initial'),
        ('dentist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='dentist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='dentist.dentistprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='account.patientprofile'),
        ),
        migrations.AddField(
            model_name='appointmentdecision',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentrefund',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='arrivalverification',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_verification', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='arrivalverification',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dentist.dentistprofile'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='dentist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='dentist.dentistprofile'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='account.patientprofile'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='treatment_interest',
            field=models.ManyToManyField(blank=True, null=True, to='core.procedure'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='appointments.consultation'),
        ),
        migrations.AddField(
            model_name='consultationdentalhistory',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dental_history', to='appointments.consultation'),
        ),
        migrations.AddField(
            model_name='consultationdentalphoto',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dental_photo', to='appointments.consultation'),
        ),
        migrations.AddField(
            model_name='consultationschedule',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='appointments.consultation'),
        ),
        migrations.AddField(
            model_name='consultationxray',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xrays', to='appointments.consultation'),
        ),
        migrations.AddField(
            model_name='escrowpayment',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_payment', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentrefund',
            name='escrow_payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund', to='appointments.escrowpayment'),
        ),
        migrations.AddField(
            model_name='finaltreatmentdecision',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_decision', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='paymentreleasecode',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='release_code', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='treatmentcompletion',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='treatmentcompletionfile',
            name='completion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='appointments.treatmentcompletion'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='appointments.consultation'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_plans', to='dentist.dentistprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='final_treatment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_appointments', to='appointments.treatmentplan'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='initial_treatment_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initial_appointments', to='appointments.treatmentplan'),
        ),
        migrations.AddField(
            model_name='treatmentplanfile',
            name='treatment_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='appointments.treatmentplan'),
        ),
        migrations.AddField(
            model_name='treatmentplanprocedure',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.procedure'),
        ),
        migrations.AddField(
            model_name='treatmentplanprocedure',
            name='treatment_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='appointments.treatmentplan'),
        ),
        migrations.AddField(
            model_name='treatmentresultphoto',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_photos', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='treatmentreview',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='treatmentreview',
            name='dentist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_review', to='dentist.dentistprofile'),
        ),
        migrations.AddField(
            model_name='treatmentreview',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_review', to='account.patientprofile'),
        ),
        migrations.AddField(
            model_name='videoconsultationsession',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_session', to='appointments.consultation'),
        ),
    ]
