# Generated by Django 6.0.5 on 2026-06-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationdentalhistory',
            name='last_dentist_visit',
            field=models.CharField(blank=True, choices=[('MONTH_6', 'Less than 6 month age'), ('MONTH_12', '6-2 month age'), ('MONTH_OVER_12', 'over a year age')], max_length=20, null=True),
        ),
    ]
