# Generated by Django 6.0.5 on 2026-06-14 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_consultationdentalhistory_last_dentist_visit'),
        ('dentist', '0011_alter_clinicalpathverification_verified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationschedule',
            name='dentist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dentist.dentistprofile'),
        ),
    ]
