# Generated by Django 6.0.5 on 2026-06-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_consultationschedule_dentist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='rough_budget_max',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='rough_budget_min',
        ),
        migrations.AddField(
            model_name='consultation',
            name='approximate_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
