# Generated by Django 6.0.5 on 2026-06-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_remove_consultation_rough_budget_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationdentalphoto',
            name='upper_arch',
            field=models.ImageField(blank=True, null=True, upload_to='consultation/dental-photo/'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('SUBMITTED', 'Submitted'), ('pending_review', 'Pending Review'), ('waiting_for_scheduling', 'Waiting for Scheduling'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('estimate_pending', 'Estimate Pending'), ('estimate_received', 'Estimate Received'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='consultationdentalphoto',
            name='front_smile',
            field=models.ImageField(blank=True, null=True, upload_to='consultation/dental-photo/'),
        ),
        migrations.AlterField(
            model_name='consultationdentalphoto',
            name='left_side',
            field=models.ImageField(blank=True, null=True, upload_to='consultation/dental-photo/'),
        ),
        migrations.AlterField(
            model_name='consultationdentalphoto',
            name='lower_arch',
            field=models.ImageField(blank=True, null=True, upload_to='consultation/dental-photo/'),
        ),
        migrations.AlterField(
            model_name='consultationdentalphoto',
            name='right_side',
            field=models.ImageField(blank=True, null=True, upload_to='consultation/dental-photo/'),
        ),
        migrations.AlterField(
            model_name='consultationdentalphoto',
            name='wide_smile',
            field=models.ImageField(blank=True, null=True, upload_to='consultation/dental-photo/'),
        ),
    ]
