# Generated by Django 6.0.5 on 2026-06-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_consultation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationreschedulerequest',
            name='timezone',
            field=models.CharField(default='EST', max_length=50),
        ),
        migrations.AlterField(
            model_name='consultationschedule',
            name='timezone',
            field=models.CharField(default='EST', max_length=50),
        ),
    ]
