# Generated by Django 6.0.5 on 2026-06-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_consultationreschedulerequest_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowpayment',
            name='payment_details',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
