# Generated by Django 6.0.5 on 2026-06-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_escrowpayment_payment_details'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('AWAITING_RESPONSE', 'Awaiting Response'), ('REJECTED', 'Rejected'), ('CONFIRMED', 'Confirmed'), ('ARRIVED', 'Arrived'), ('IN_PROGRESS', 'In Progress'), ('final_estimate_submit', 'Final Estimate Submit'), ('PAYMENT_RELEASE_PENDING', 'Payment Release Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='AWAITING_RESPONSE', max_length=30),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='treatment_interest',
            field=models.ManyToManyField(blank=True, to='core.procedure'),
        ),
        migrations.AlterField(
            model_name='escrowpayment',
            name='payment_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
