# Generated by Django 6.0.5 on 2026-06-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentplan',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
