# Generated by Django 6.0.5 on 2026-06-16 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_patientprofile_gender_user_gender'),
        ('appointments', '0011_alter_treatmentplan_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowpayment',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrowpayment',
            name='invoice_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='escrowpayment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='account.patientprofile'),
        ),
        migrations.AddField(
            model_name='escrowpayment',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='escrowpayment',
            name='provider_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='escrowpayment',
            name='receipt_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='escrowpayment',
            name='refunded_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='escrowpayment',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='escrowpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('AWAITING_RESPONSE', 'Awaiting Response'), ('CONFIRMED', 'Confirmed'), ('ARRIVED', 'Arrived'), ('IN_PROGRESS', 'In Progress'), ('final_estimate_submit', 'Final Estimate Submit'), ('PAYMENT_RELEASE_PENDING', 'Payment Release Pending'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='AWAITING_RESPONSE', max_length=30),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('estimate_pending', 'Estimate Pending'), ('estimate_received', 'Estimate Received'), ('treatment_accept', 'Treatment Accept'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='escrowpayment',
            name='payment_details',
            field=models.JSONField(default=dict),
        ),
    ]
