# Generated by Django 6.0.5 on 2026-06-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_escrowpayment_failure_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('AWAITING_RESPONSE', 'Awaiting Response'), ('AWAITTING_FOR_PAYMENT', 'Awaitting For Payment'), ('CONFIRMED', 'Confirmed'), ('ARRIVED', 'Arrived'), ('IN_PROGRESS', 'In Progress'), ('final_estimate_submit', 'Final Estimate Submit'), ('PAYMENT_RELEASE_PENDING', 'Payment Release Pending'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='AWAITING_RESPONSE', max_length=30),
        ),
    ]
