# Generated by Django 6.0.5 on 2026-06-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentcompletionfile',
            name='title',
        ),
    ]
