# Generated by Django 6.0.5 on 2026-06-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_remove_treatmentcompletionfile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentrefund',
            name='patient_note',
        ),
        migrations.RemoveField(
            model_name='treatmentplanfile',
            name='title',
        ),
    ]
