# Generated by Django 6.0.5 on 2026-06-21 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_patientprofile_gender_user_gender'),
        ('appointments', '0016_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escrowpayment',
            name='failure_reason',
        ),
        migrations.RemoveField(
            model_name='escrowpayment',
            name='invoice_url',
        ),
        migrations.RemoveField(
            model_name='escrowpayment',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='escrowpayment',
            name='payment_details',
        ),
        migrations.RemoveField(
            model_name='escrowpayment',
            name='payment_provider',
        ),
        migrations.RemoveField(
            model_name='escrowpayment',
            name='provider_transaction_id',
        ),
        migrations.RemoveField(
            model_name='escrowpayment',
            name='receipt_url',
        ),
        migrations.RemoveField(
            model_name='escrowpayment',
            name='refunded_amount',
        ),
        migrations.RemoveField(
            model_name='escrowpayment',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='escrowpayment',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='escrowpayment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_payment', to='account.patientprofile'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INITIAT', 'Initiat'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUND', 'Refund'), ('PARTIAL_REFUND', 'Partial Refund')], default='PENDING', max_length=30)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_details', models.JSONField(default=dict)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('invoice_url', models.CharField(blank=True, max_length=255, null=True)),
                ('receipt_url', models.CharField(blank=True, max_length=255, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='appointments.appointment')),
                ('escrow_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='appointments.escrowpayment')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='account.patientprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
