# Generated by Django 6.0.5 on 2026-06-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0017_remove_escrowpayment_failure_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowpayment',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
